export enum ACTION {
    GET_SERVER_CONFIGS='getServerConfigs',
    CREATE_TRANSPORT='createTransport', CONNECT_TRANSPORT='connectTransport', CLOSE_TRANSPORT='closeTransport',
    PRODUCE='produce', CONSUME='consume',
    RESUME_CONSUMER='resumeConsumer',PAUSE_CONSUMER='pauseConsumer',CLOSE_CONSUMER='closeConsumer',
    RESUME_PRODUCER='resumeProducer',PAUSE_PRODUCER='pauseProducer',CLOSE_PRODUCER='closeProducer',
    FILE_STREAMING='fileStreaming', RTMP_STREAMING='rtmpStreaming', STOP_FILE_STREAMING='stopFileStreaming',
    START_RECORDING="startRecording", STOP_RECORDING="stopRecording",
    CREATE_PIPE_TRANSPORT='createPipeTransport', CONNECT_PIPE_TRANSPORT='connectPipeTransport',
    SET_PREFERRED_LAYERS="setPreferredLayers",SET_MAX_INCOMING_BITRATE='setMaxIncomingBitrate',
    PRODUCERS_STATS='producersStats', CONSUMERS_STATS='consumersStats', TRANSPORT_STATS='transportStats',
    PIPE_TO_REMOTE_PRODUCER='pipeToRemoteProducer', PIPE_FROM_REMOTE_PRODUCER='pipeFromRemoteProducer',
    WORKER_LOAD='workerLoad', NUM_WORKERS='numWorkers',
    RECORDED_STREAMS='recordedStreams', STREAM_RECORDINGS='streamRecordings',
    DELETE_STREAM_RECORDINGS='deleteStreamRecordings', DELETE_RECORDING='deleteRecording',
    PUSH_TO_SERVER_INPUTS='pushToServerInputs', PULL_FROM_SERVER_INPUTS='pullFromServerInputs',
    PUSH_TO_SERVER_OPTIONS='pushToServerOptions', PUSH_TO_SERVER='pushToServer',
    KINDS_BY_FILE='kindsByFile',REQUEST_KEYFRAME='requestKeyframe'
}

export const SOCKET_ACTIONS=Object.values(ACTION);

export enum PATH {
    RECORDINGS="recordings",
    MEDIASOUP="mediasoup",
    FRONT="front",
    API_DOCS="api-docs"}
export enum ERROR {UNKNOWN=500,UNAUTHORIZED=401,INVALID_TRANSPORT=530,INVALID_PRODUCER=531,INVALID_CONSUMER=532,INVALID_STREAM=533,INVALID_OPERATION=534,INVALID_WORKER=535,INVALID_INPUT=536}
export enum API_OPERATION {SUBSCRIBE,PUBLISH,RECORDING,STREAMING}
export const API_OPERATION_BY_ACTION={
    [ACTION.PRODUCE]: API_OPERATION.PUBLISH,

    [ACTION.RECORDED_STREAMS]: API_OPERATION.RECORDING,
    [ACTION.STREAM_RECORDINGS]: API_OPERATION.RECORDING,
    [ACTION.DELETE_STREAM_RECORDINGS]: API_OPERATION.RECORDING,
    [ACTION.STREAM_RECORDINGS]: API_OPERATION.RECORDING,
    [ACTION.START_RECORDING]: API_OPERATION.RECORDING,
    [ACTION.STOP_RECORDING]: API_OPERATION.RECORDING,

    [ACTION.FILE_STREAMING]: API_OPERATION.STREAMING,
    [ACTION.STOP_FILE_STREAMING]: API_OPERATION.STREAMING,
    [ACTION.RTMP_STREAMING]: API_OPERATION.STREAMING

};